{
 "title": "Seneye",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "((avg(temperature_celsius) by (id, name))*(9/5))+32"
    }
   ]
  },
  {
   "title": "pH",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pH" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "avg(ph) by (id, name)" }
   ]
  },
  {
   "title": "Free Ammonia (NH3)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(ammonia)" }
   ]
  },
  {
   "title": "Water Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "yaxes": [
    { "format": "fahrenheit" }
   ],
   "targets": [
    {
     "expr": "((avg (temperature_celsius) by (id, name)) * (9/5)) + 32",
     "legendFormat": "{{ name }} ({{ id }})"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "max(seneye_status_slide)", "legendFormat": "Slide" },
    { "expr": "max(seneye_status_ph)", "legendFormat": "pH" },
    { "expr": "max(seneye_status_ammonia)", "legendFormat": "Ammonia (NH3)" },
    { "expr": "max(seneye_status_temperature)", "legendFormat": "Temperature" },
    { "expr": "1-max(seneye_status_water)", "legendFormat": "Water" },
    { "expr": "max(seneye_status_kelvin)", "legendFormat": "Kelvin" }
   ]
  },
  {
   "title": "Free Ammonia (NH3)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "yaxes": [
    { "format": "ppm" }
   ],
   "targets": [
    { "expr": "avg(ammonia) by (name, id)", "legendFormat": "{{ name }} ({{ id }})" }
   ]
  },
  {
   "title": "pH",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "avg(ph) by (name, id)", "legendFormat": "{{ name }} ({{ id }})" }
   ]
  },
  {
   "title": "Light (LUX)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "avg (light_lux) by (id, name)", "legendFormat": "{{ name }} ({{ id }})" }
   ]
  }
 ]
}